### ISSUE TITLE
performance-measurement test harness does not compile on main (Embeddings events uncovered)

### ISSUE THREAD

**Issue by aosama** [aosama/astronomical#672]
## Problem

`performance_measurement_tests` does not compile on `main` (nor on the v0.2.43 / v0.2.44 release tags). The `WorkerEvent` match in `apps/inference-worker/tests/model_ssd_streaming/prefill_chunk_sweep.rs` does not cover the three embeddings event variants added to `crates/ipc-protocol`:

```
error[E0004]: non-exhaustive patterns: `WorkerEvent::EmbeddingsCompleted { .. }`, `WorkerEvent::EmbeddingsFailed { .. }` and `WorkerEvent::EmbeddingsFinalized { .. }` not covered
```

This means the model SSD-streaming prefill measurement journeys (for example `scripts/run-disposable-cargo-journey.sh measure-model-ssd-streaming-summary`) cannot build, so attributed prefill/generation TPS baselines have been unavailable since the embeddings events landed. Confirmed on:

- `main` @ `b72e14c` (v0.2.44 code) — fails
- tag `v0.2.43` @ `26c5b04` — fails

## Scope

Test-only fix. Treat embeddings events like the existing image-generation events in that match: an autoregressive prefill benchmark must never receive them, so panic if one arrives rather than failing exhaustiveness.

## Acceptance criteria

- [ ] `cargo test --release -p astronomical-inference-worker --test performance_measurement_tests --features performance-measurement should_measure_model_ssd_streaming_summarization_throughput_and_peak_memory -- --ignored --nocapture` builds and the measurement runs to completion.
- [ ] The fix compiles the whole `performance_measurement_tests` harness (including `prefill_chunk_sweep.rs`'s `model_ssd_streaming` module).
